# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
gpu_id: '0'
val_interval:
 rating: "[0,3);(3,inf)"
threshold:
   rating: 4
load_col:
   inter: [user_id, item_id, rating]
   user: [user_id, age, gender, occupation]
   item: [item_id, genre, release_year]


epochs: 500
train_batch_size: 4096
eval_batch_size: 4096

eval_args:
 split: {'RS':[0.8, 0.1, 0.1]}
 group_by: ~
 mode: labeled
 order: RO
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
show_progress: False
stopping_step : 2
embedding_size : 16

checkpoint_dir: saved/ml-1m
gpu_id: '6'


#deepfm
dropout_prob: 0.4
learning_rate: 0.001
mlp_hidden_size: [256,256,256]
